### ISSUE TITLE
Scrolling in Edge not working

### ISSUE THREAD

**Issue by OssianEriksson** [ECarlsson/foton#28]
Is Edge supposed to be supported? If so, scrolling in the galleries isnt working.

**Comment by ECarlsson** [comment]
Cannot replicate, could this be related to issue #24?

**Comment by ECarlsson** [comment]
Fixed in 917765b0fb4460d40a299954576ac71902c0c765

**Comment by ECarlsson** [comment]
Cannot replicate, issue closed.
